import { MMTAsset } from '../demux/mmt-si';
import { MMTPEncryptionFlag, MMTPPayloadType, MMTPScramblingInfo } from '../demux/mmtp';
import { H265NaluHVC1 } from '../demux/h265';
import { LOASAACFrame } from '../demux/aac';
import { MMTSAudioTrackInfo, MMTSSubtitleTrackInfo, MMTSVideoTrackInfo } from '../demux/mmts-track-data';
export declare function isH265VclNalu(naluType: number): boolean;
export declare function isH265IrapNalu(naluType: number): boolean;
export declare function hasVideoParameterSets(units: H265NaluHVC1[]): boolean;
export declare function hasH265CraNalu(units: H265NaluHVC1[]): boolean;
export declare function hasH265IdrNalu(units: H265NaluHVC1[]): boolean;
export declare function hasH265RaslNalu(units: H265NaluHVC1[]): boolean;
export declare function hasH265PostCraTrailingVclNalu(units: H265NaluHVC1[]): boolean;
export declare function readH265NaluType(unit: Uint8Array): number;
export declare function compareMMTSVideoTrackPriority(a: MMTSVideoTrackInfo, b: MMTSVideoTrackInfo): number;
export declare function findMMTSPrimaryVideoTrack(tracks: MMTSVideoTrackInfo[]): MMTSVideoTrackInfo | undefined;
export declare function findMMTSSecondaryVideoTrack(tracks: MMTSVideoTrackInfo[], primaryTrack: MMTSVideoTrackInfo | undefined): MMTSVideoTrackInfo | undefined;
export declare function isMMTSVideoFallback(tracks: MMTSVideoTrackInfo[], selectedPacketId: number): boolean;
export declare function getMMTSSelectedVideoRole(tracks: MMTSVideoTrackInfo[], selectedPacketId: number, fallback: boolean): 'primary' | 'secondary' | undefined;
export declare function audioSampleRateFromCode(code: number | undefined): number | undefined;
export declare function audioLayoutFromComponentType(componentType: number | undefined): string | undefined;
export declare function audioChannelCountFromComponentType(componentType: number | undefined): number | undefined;
export declare function audioLayoutFromAacConfig(channelConfig: number): string | undefined;
export declare function audioChannelCountFromAacConfig(channelConfig: number): number | undefined;
export declare function isSupportedAACChannelConfig(channelConfig: number): boolean;
export declare function hasKnownMMTSAudioSupport(info: MMTSAudioTrackInfo | undefined): boolean;
export declare function isMMTSAudioTrackSelectable(info: MMTSAudioTrackInfo | undefined): boolean;
export declare function scoreAudioTrack(track: MMTSAudioTrackInfo): number;
export declare function findPreferredAudioTrack(tracks: MMTSAudioTrackInfo[], requireKnownSupport: boolean): MMTSAudioTrackInfo | undefined;
export declare function getSortedAudioTrackInfos(tracksByPacketId: {
    [packetId: number]: MMTSAudioTrackInfo;
}): MMTSAudioTrackInfo[];
export declare function getSortedVideoTrackInfos(tracksByPacketId: {
    [packetId: number]: MMTSVideoTrackInfo;
}): MMTSVideoTrackInfo[];
export declare function getSortedSubtitleTrackInfos(tracksByPacketId: {
    [packetId: number]: MMTSSubtitleTrackInfo;
}): MMTSSubtitleTrackInfo[];
export declare function createMMTSVideoTrackInfo(asset: MMTAsset, previous: MMTSVideoTrackInfo | undefined, active: boolean, selected: boolean): MMTSVideoTrackInfo;
export declare function createMMTSAudioTrackInfo(asset: MMTAsset, previous: MMTSAudioTrackInfo | undefined, selected: boolean): MMTSAudioTrackInfo;
export declare function createMMTSSubtitleTrackInfo(asset: MMTAsset, previous: MMTSSubtitleTrackInfo | undefined): MMTSSubtitleTrackInfo;
export declare function updateMMTSAudioTrackInfoFromFrame(packetId: number, frame: LOASAACFrame, previous: MMTSAudioTrackInfo | undefined, selected: boolean): MMTSAudioTrackInfo;
export declare function videoResolutionLabel(asset: MMTAsset): string;
export declare function toHex(data: Uint8Array): string;
export declare function formatHex(value: number, width: number): string;
export declare function formatMsTimestamp(value: number, timescale: number): number;
export declare function formatH265NaluTypes(units: H265NaluHVC1[]): string;
export declare function formatPacketCounts(counts: {
    [packetId: number]: number;
}): string;
export declare function mmtLocationTypeName(locationType: number): string;
export declare function layerTypeName(layerType: number | undefined): string;
export declare function scrambleSystemName(systemId: number): string;
export declare function formatAssetConditionalAccessInfo(asset: MMTAsset): string;
export declare function readU16(data: Uint8Array, offset: number): number;
export declare function readU32(data: Uint8Array, offset: number): number;
export declare function payloadTypeName(payloadType: MMTPPayloadType): string;
export declare function formatMmtpScramblingInfo(info: MMTPScramblingInfo | undefined): string;
export declare function scramblingName(encryptionFlag: MMTPEncryptionFlag | undefined): string;
