import BaseDemuxer from './base-demuxer';
declare class MMTSDemuxer extends BaseDemuxer {
    private readonly TAG;
    private config_;
    private stash_;
    private parsed_packet_count_;
    private parsed_mmtp_count_;
    private last_summary_tlv_count_;
    private tlv_packet_type_counts_;
    private mmtp_packet_id_counts_;
    private signaling_fragment_states_;
    private mfu_fragment_states_;
    private assets_by_packet_id_;
    private logged_asset_keys_;
    private logged_mpu_header_count_;
    private logged_mfu_unit_count_;
    private primary_video_packet_id_;
    private media_info_;
    private video_metadata_;
    private video_track_;
    private video_init_segment_dispatched_;
    private video_sample_index_;
    private video_started_;
    private current_video_access_unit_;
    constructor(probeData: any, config: any);
    destroy(): void;
    static probe(buffer: ArrayBuffer): import("./tlv").TLVProbeResult;
    bindDataSource(loader: any): this;
    parseChunks(chunk: ArrayBuffer, byteStart: number): number;
    private parseSignalingMessages;
    private parseMpu;
    private assembleMfuFragment;
    private appendToState;
    private logCompleteMfuUnit;
    private processCompleteMfuUnit;
    private appendH265NaluToAccessUnit;
    private flushCurrentVideoAccessUnit;
    private appendStandaloneVideoSample;
    private isH265VclNalu;
    private dispatchVideoInitSegment;
    private dispatchVideoMediaSegment;
    private logSummary;
    private formatHex;
    private payloadTypeName;
    private scramblingName;
    private fragmentTypeName;
    private fragmentationName;
}
export default MMTSDemuxer;
