import BaseDemuxer from './base-demuxer';
declare class MMTSDemuxer extends BaseDemuxer {
    private readonly TAG;
    private config_;
    private stash_;
    private parsed_mmtp_count_;
    private program_;
    private pending_mfu_units_by_packet_id_;
    private logged_asset_keys_;
    private logged_video_timestamp_fallback_count_;
    private logged_video_timestamp_correction_count_;
    private logged_audio_timestamp_fallback_count_;
    private logged_unsupported_audio_packet_ids_;
    private audio_track_infos_by_packet_id_;
    private subtitle_track_infos_by_packet_id_;
    private audio_parse_states_by_packet_id_;
    private audio_tracks_signature_;
    private subtitle_tracks_signature_;
    private dropped_video_sample_count_;
    private last_video_dts_;
    private last_video_pts_;
    private last_video_duration_;
    private output_video_dts_base_;
    private primary_video_packet_id_;
    private primary_audio_packet_id_;
    private media_info_;
    private audio_metadata_;
    private video_metadata_;
    private audio_track_;
    private video_track_;
    private audio_init_segment_dispatched_;
    private video_init_segment_dispatched_;
    private audio_last_sample_pts_;
    private aac_last_incomplete_data_;
    private loas_previous_frame_;
    private video_sample_index_;
    private video_started_;
    private current_video_access_unit_;
    private pre_init_video_units_;
    constructor(probeData: any, config: any);
    destroy(): void;
    static probe(buffer: ArrayBuffer): import("./tlv").TLVProbeResult;
    bindDataSource(loader: any): this;
    parseChunks(chunk: ArrayBuffer, byteStart: number): number;
    private parseSignalingMessages;
    private parseMpu;
    private processCompleteMfuUnit;
    private appendH265NaluToAccessUnit;
    private processAudioMfuUnit;
    private wrapLatmPayloadWithLoasHeader;
    private parseMMTSLOASAACPayload;
    private processSubtitleMfuUnit;
    private extractSubtitlePayload;
    private flushCurrentVideoAccessUnit;
    private appendStandaloneVideoSample;
    private consumeVideoTimestamp;
    private consumeAudioTimestamp;
    private isH265VclNalu;
    private isH265IrapNalu;
    private maybeSelectPrimaryAudioAsset;
    selectAudioTrack(packetId: number): boolean;
    selectPrimaryAudioTrack(): void;
    selectSecondaryAudioTrack(): void;
    private maybeSelectPrimaryVideoAsset;
    private getForcedMMTSVideoPacketId;
    private scorePendingVideoAsset;
    private resetVideoBootstrapState;
    private updateTrackInfo;
    private updateAudioTrackInfoFromFrame;
    private maybePromotePrimaryAudioTrack;
    private hasKnownMMTSAudioSupport;
    private isMMTSAudioTrackSelectable;
    private isSupportedAACChannelConfig;
    private logUnsupportedMMTSAudioTrack;
    private getAudioParseState;
    private dispatchAudioTracksIfChanged;
    private dispatchSubtitleTracksIfChanged;
    private getSortedAudioTrackInfos;
    private getSortedSubtitleTrackInfos;
    private audioSampleRateFromCode;
    private audioLayoutFromComponentType;
    private audioChannelCountFromComponentType;
    private audioLayoutFromAacConfig;
    private audioChannelCountFromAacConfig;
    private logSubtitleData;
    private toHex;
    private detectAudioMetadataChange;
    private readH265NaluType;
    private cachePendingMfuUnit;
    private replayPendingMfuUnits;
    private cachePreInitVideoUnit;
    private replayPreInitVideoUnits;
    private dispatchAudioInitSegment;
    private dispatchAudioMediaSegment;
    private dispatchVideoInitSegment;
    private dispatchVideoMediaSegment;
    private formatHex;
    private readU16;
    private readU32;
    private payloadTypeName;
    private scramblingName;
}
export default MMTSDemuxer;
