export type ForwardBufferInfo = {
    currentTime: number;
    forwardDuration?: number;
    audioForwardDuration?: number;
    videoForwardDuration?: number;
    forwardBytes: number;
    audioForwardBytes?: number;
    videoForwardBytes?: number;
};
export type ForwardBufferInfoProvider = () => ForwardBufferInfo | null;
declare class LoadingController {
    private _config;
    private _media_element;
    private _on_pause_transmuxer;
    private _on_resume_transmuxer;
    private _get_forward_buffer_info?;
    private _paused;
    private _suspend_due_to_duration;
    private _suspend_due_to_bytes;
    private e?;
    constructor(config: any, media_element: HTMLMediaElement, on_pause_transmuxer: () => void, on_resume_transmuxer: () => void, get_forward_buffer_info?: ForwardBufferInfoProvider);
    destroy(): void;
    notifyBufferedPositionChanged(_buffered_position?: number): void;
    private _onMediaWaitingOrStalled;
    private _onMediaTimeUpdate;
    private _suspendTransmuxerIfNeeded;
    private _getForwardBufferWindow;
    private _getForwardBufferHorizonDuration;
    private _isLazyLoadEnabled;
    private _usesMSEBufferStateMachine;
    private _getForwardBufferInfo;
    private _isOptionalForwardBytesValid;
    private _isOptionalForwardDurationValid;
    private _getVideoForwardBytes;
    private _getVideoForwardDuration;
    private _getLazyLoadMaxDuration;
    private _getLazyLoadRecoverDuration;
    private _getLazyLoadMaxBytes;
    private _getLazyLoadRecoverBytes;
    private _normalizeByteLimit;
    suspendTransmuxer(): void;
    suspendTransmuxerUntilRecover(): void;
    private _resumeTransmuxerIfNeeded;
    resumeTransmuxer(): void;
}
export default LoadingController;
