import { type PlaybackOperation } from '../core/playback-operation';
import { type MMTSStartupGroupFailure } from '../core/mmts-startup-group-lifecycle';
export type MSEBufferTrackType = 'video' | 'audio';
export type MSEStartupGroup = {
    playbackOperation?: PlaybackOperation;
    mseBufferGeneration?: number;
    videoInitSegment: any;
    audioInitSegment?: any;
    videoMediaSegment: any;
    audioMediaSegment?: any;
    startupTime: number;
    videoDecodeStart: number;
    videoCompositionStart: number;
    audioStart?: number;
    audioEnd?: number;
    syncPoint: number;
    playableStart: number;
    playableEnd: number;
    hasAudio: boolean;
    hasVideo: boolean;
};
export type MSEBufferMainState = 'DETACHED' | 'OPENING' | 'PRIMING' | 'STEADY' | 'BACKPRESSURE' | 'EVICTING' | 'RECOVERING' | 'SEEKING' | 'TRACK_SWITCHING' | 'DRAINING_EOS' | 'ENDED' | 'FATAL';
export type MSEBufferTrackState = 'NO_SOURCEBUFFER' | 'NEED_INIT' | 'READY' | 'APPENDING' | 'REMOVING' | 'BLOCKED_BY_BUDGET' | 'BLOCKED_BY_LEAD' | 'BLOCKED_BY_QUOTA' | 'RESETTING_PARSER';
type MSEBufferOperationResult = {
    ok?: boolean;
    blocked?: boolean;
    quota?: boolean;
    fatal?: boolean;
    empty?: boolean;
    error?: any;
};
type MSEBufferRange = {
    start: number;
    end: number;
    kind?: 'cleanup' | 'flush';
};
type MSEBufferForwardInfo = {
    currentTime: number;
    forwardBytes: number;
    forwardDuration?: number;
    audioForwardBytes?: number;
    videoForwardBytes?: number;
    audioBufferedBytes?: number;
    videoBufferedBytes?: number;
    audioForwardDuration?: number;
    videoForwardDuration?: number;
    playableEnd?: number;
};
type MSEBufferMediaSourceState = {
    readyState: string;
    streaming?: boolean;
    hasFatalMediaError?: boolean;
    hasPendingRemoveRanges?: boolean;
    sourceBuffers: {
        video?: {
            exists: boolean;
            updating: boolean;
        };
        audio?: {
            exists: boolean;
            updating: boolean;
        };
    };
};
export type MSEAudioTrackSwitchRebuildPlan = {
    type: 'audio_track_switch';
    operation: PlaybackOperation;
    replaceMediaSource: boolean;
    preserveVideoBuffer: boolean;
    switchTime: number;
    seekTime: number;
    resumePlayback: boolean;
    videoInitSegment: any;
    audioInitSegment: any;
    videoSegments: any[];
    audioSegments: any[];
    transactionId: number;
};
export type MSETrackSwitchFailurePhase = 'plan-validation' | 'rebuild-media-source' | 'reset-parser-state' | 'append-init' | 'append-media' | 'mse-fatal';
export type MSETrackSwitchFailure = {
    kind: 'audio-switch' | 'video-switch';
    operation: PlaybackOperation;
    transactionKey: string;
    attemptKey: string;
    transactionId: number;
    phase: MSETrackSwitchFailurePhase;
    error: any;
};
export type MSEBufferStateMachineOutput = {
    ensureSourceBuffer?: (type: MSEBufferTrackType, segment: any) => MSEBufferOperationResult;
    appendInit: (type: MSEBufferTrackType, segment: any) => MSEBufferOperationResult;
    appendMedia: (type: MSEBufferTrackType, segment: any) => MSEBufferOperationResult;
    removeRange: (type: MSEBufferTrackType, start: number, end: number) => MSEBufferOperationResult;
    resetParserState: (type: MSEBufferTrackType, mimeType: string) => MSEBufferOperationResult;
    rebuildMediaSource: (plan: MSEAudioTrackSwitchRebuildPlan) => boolean;
    pauseTransmuxer: (reason: string) => void;
    resumeTransmuxer: (reason: string) => void;
    flushPending: (type?: MSEBufferTrackType) => void;
    emitFatal: (error: any) => void;
    onStartupGroupAppended?: (startupGroup: MSEStartupGroup) => void;
    onAudioTrackSwitchRebuildComplete?: (operation: PlaybackOperation) => void;
    onAudioTrackSwitchRebuildFailed?: (failure: MSETrackSwitchFailure) => void;
    onVideoTrackSwitchComplete?: (operation: PlaybackOperation) => void;
    onVideoTrackSwitchFailed?: (failure: MSETrackSwitchFailure) => void;
    onPlaybackOperationComplete?: (operation: PlaybackOperation, details?: {
        committedTimeMilliseconds?: number;
    }) => void;
    onPlaybackOperationFailed?: (operation: PlaybackOperation, error: any) => void;
    seekMedia?: (targetTime: number, reason: string) => void;
    seekTransmuxer?: (milliseconds: number, reason: string, operation?: PlaybackOperation) => void;
    endOfStream?: () => MSEBufferOperationResult;
    getMediaSourceState?: () => MSEBufferMediaSourceState;
    getForwardBufferInfo?: (currentTime: number) => MSEBufferForwardInfo;
    getBufferedRanges?: (type: MSEBufferTrackType) => MSEBufferRange[];
};
declare class MSEBufferStateMachine {
    private readonly TAG;
    private _config;
    private _output;
    private _main_state;
    get isFatal(): boolean;
    private _track_state;
    private _pending_init_segments;
    private _pending_media_segments;
    private _pending_remove_ranges;
    private _pending_full_track_flush;
    private _pending_track_flush_from;
    private _current_time;
    private _ready_state;
    private _source_opened;
    private _transmuxer_paused;
    private _transmuxer_pause_reason;
    private _backpressure_stall_prefetch_active;
    private _backpressure_stall_prefetch_start_time;
    private _pending_eos;
    private _inflight_operations;
    private _seek_generation;
    private _playback_operation;
    private _last_quota_type;
    private _media_info;
    private _pending_media_seek_target;
    private _pending_media_seek_reason;
    private _pending_media_seek_min_forward;
    private _pending_transmuxer_seek_milliseconds;
    private _pending_transmuxer_seek_reason;
    private _timeline_seek_target_time;
    private _track_switch_needs_data;
    private _live_audio_track_switch_collection_hold;
    private _pending_audio_rebuild_plan;
    private _pending_audio_rebuild_operation;
    private _track_switch_transaction;
    private _failed_track_switch_transactions;
    private _last_failed_track_switch;
    private _mmts_vod_audio_track_rebuild_active;
    private _pending_startup_group;
    private _pending_startup_group_id;
    private _pending_startup_group_media;
    private _pending_startup_group_timer;
    private _startup_group_timeout;
    private _last_mmts_source_identity;
    private _video_random_access_points;
    constructor(config: any, output: MSEBufferStateMachineOutput);
    destroy(): void;
    onSourceOpen(): void;
    canSetPlaybackOperation(operation: PlaybackOperation): boolean;
    setPlaybackOperation(operation: PlaybackOperation): boolean;
    onInitSegment(type: MSEBufferTrackType, segment: any): void;
    onMediaSegment(type: MSEBufferTrackType, segment: any): void;
    onMediaInfo(mediaInfo: any): void;
    onStartupGroup(startupGroup: MSEStartupGroup): void;
    onStartupGroupFailure(failure: MMTSStartupGroupFailure): void;
    onUpdateEnd(type?: MSEBufferTrackType): void;
    onRemoveUpdateEnd(type?: MSEBufferTrackType): void;
    onQuotaExceeded(type?: MSEBufferTrackType, segment?: any): void;
    onMediaState(currentTime: number, readyState: number, eventType: string): void;
    onContinuousBufferStall(): boolean;
    onSeek(targetTime: number): void;
    onDirectSeek(targetTime: number): boolean;
    onRecommendedSeekPoint(targetTime: number): void;
    onUserSeek(targetTime: number): void;
    onMMTSVodAudioTrackRebuild(targetTime: number, operation?: PlaybackOperation, transactionId?: number): boolean;
    cancelAudioTrackSwitch(operation: PlaybackOperation): boolean;
    cancelMMTSVodAudioTrackRebuild(): void;
    private _beginTimelineSeek;
    onAudioTrackSwitch(request: any): boolean;
    onVideoTrackSwitch(request: any): boolean;
    cancelVideoTrackSwitch(operation: PlaybackOperation): boolean;
    private _getVideoTrackSwitch;
    private _queueVideoTrackSwitchCommit;
    private _doesVideoSwitchMatchMediaWindow;
    private _isExactVideoTrackSwitch;
    private _isVideoTrackSwitchIdentity;
    private _makeTrackSwitchTransactionContext;
    private _isSameTrackSwitchContext;
    private _isTrackSwitchRequestCurrent;
    private _rejectTrackSwitchRequest;
    private _failOrRejectTrackSwitchRequest;
    private _failTrackSwitch;
    private _clearTrackSwitchTransactionState;
    private _trackSwitchFailureKey;
    private _enterFatal;
    onMediaElementError(error: any): void;
    onEndOfStream(operation?: PlaybackOperation): void;
    onFatal(error: any): void;
    onExternalMSEError(error: any): void;
    tick(reason: string): void;
    flushPending(type?: MSEBufferTrackType): void;
    private _queueStartupInitSegment;
    private _queueStartupMediaSegment;
    private _isStartupGroupUsable;
    private _isStartupGroupOperationConsistent;
    private _doesStartupVideoCoverPlayableWindow;
    private _markStartupGroupMediaAppended;
    private _markVideoTrackSwitchMediaAppended;
    private _markAudioTrackSwitchMediaAppended;
    private _finishVideoTrackSwitchTailTrimIfReady;
    private _resolveStartupSeekTime;
    private _findFirstRangeTime;
    private _clearPendingStartupGroup;
    private _startStartupGroupAppendWatchdog;
    private _clearStartupGroupAppendWatchdog;
    private _getPendingStartupGroupParts;
    private _getInvalidStartupGroupParts;
    private _failStartupGroup;
    private _failStartupGroupForSegment;
    getForwardBufferInfo(currentTime: number): MSEBufferForwardInfo;
    private _getBufferedForwardBufferInfo;
    private _appendRequiredInit;
    private _runPendingParserReset;
    private _appendMedia;
    private _peekMediaBatch;
    private _isMediaBatchBoundary;
    private _mergeMediaBatch;
    private _getSegmentData;
    private _runPendingRemove;
    private _runPendingTransmuxerSeek;
    private _queueAudioTrackSwitchRebuild;
    private _runPendingAudioTrackSwitchRebuild;
    private _makeAudioTrackSwitchRebuildPlan;
    private _isRebuildInitSegment;
    private _isRebuildMediaSegment;
    private _doesVideoRebuildStartAtSyncPoint;
    private _cloneRebuildInitSegment;
    private _cloneRebuildMediaSegment;
    private _resetMMTSSourceIdentity;
    private _isMMTSSourceIdentityValid;
    private _recordMMTSSourceIdentity;
    private _shouldValidateMMTSSourceIdentity;
    private _getSegmentMMTSSourceBegin;
    private _getSegmentMMTSSourceEnd;
    private _hasBackwardFilePosition;
    private _hasStaleMMTSSourceIdentity;
    private _hasBackwardMpuSequence;
    private _hasRepeatedSampleInSameMpu;
    private _isSameMMTSPacket;
    private _hasSevereBackwardRawDts;
    private _enterRecoveringForInvalidMMTSSourceIdentity;
    private _isFiniteNumber;
    private _isMMTS;
    private _isMMTSInputForCurrentOperation;
    private _isMMTSInputForOperation;
    private _isCurrentPlaybackOperation;
    private _isOperationForTransaction;
    private _isExactPlaybackOperation;
    private _getTrackSwitchContextForSegment;
    private _dropStaleMMTSPendingData;
    private _enterQuotaEviction;
    private _selectInitTrack;
    private _shouldDeferVideoInitUntilAudio;
    private _needsBudgetEviction;
    private _schedulePressureCleanup;
    private _scheduleNormalCleanup;
    private _scheduleBackwardCleanup;
    private _scheduleTrackFlush;
    private _materializePendingTrackFlush;
    private _scheduleTrackFlushFrom;
    private _appendRemoveRange;
    private _getCurrentPlayableRange;
    private _makeCurrentTimeProtectionRange;
    private _findRangeCoveringCurrentTime;
    private _updateBackpressure;
    private _updateBackpressureStallPrefetch;
    private _tryBeginBackpressureStallPrefetch;
    private _clearBackpressureStallPrefetch;
    private _resumeIfRecovered;
    private _canBackpressureControlTransmuxer;
    private _isBackpressureReady;
    private _scheduleAudioCleanupIfNeeded;
    private _isVideoBlockedByAudioLead;
    private _isAudioBlockedByVideoLead;
    private _getTrackLeadReferenceEnd;
    private _getPlayableForwardDuration;
    private _recordVideoRandomAccessPoints;
    private _resolveBufferedVideoRandomAccessPoint;
    private _hasPlayableRangeAt;
    private _requestMediaSeekWhenPlayable;
    private _findPlayableSeekTimeAtOrAfter;
    private _applyPendingMediaSeekIfReady;
    private _isAudioTrackSwitchRebuildReason;
    private _resumeTrackSwitchDataRequestIfReady;
    private _canLeaveTransientState;
    private _isSegmentAllowedInCurrentTimeline;
    private _isRangeCovered;
    private _expectsAudio;
    private _expectsVideo;
    private _hasAudioSourceOrPending;
    private _getSeekPrerollKeepDuration;
    private _isMediaSourceOperational;
    private _isOperationalMediaSourceState;
    private _hasFatalMediaError;
    private _canOperateOnType;
    private _canAppendMediaToType;
    private _allSourceBuffersIdle;
    private _getMediaSourceState;
    private _getSourceBufferState;
    private _setInflightOperation;
    private _getInflightOperation;
    private _takeInflightOperation;
    private _clearInflightOperation;
    private _clearAllInflightOperations;
    private _markTrackReady;
    private _queuesEmpty;
    private _hasPendingRemoveRanges;
    private _hasPendingTrackFlush;
    private _pauseTransmuxer;
    private _resumeTransmuxer;
    private _shouldReplacePauseReason;
    private _canResumeTransmuxer;
    private _getTrackLeadLimit;
    private _getAppendBatchDuration;
    private _getBaseByteLimit;
    private _getByteLimit;
    private _getRecoverVideoBytes;
    private _getRecoverAudioBytes;
    private _getForwardTargetDuration;
    private _getRecoverForwardDuration;
    private _getNormalBackwardKeepDuration;
    private _getPressureBackwardKeepDuration;
    private _isMediaSegmentTimestampValid;
    private _enterRecoveringForInvalidTimestamp;
    private _getPendingForwardBytes;
    private _getPipelineForwardDuration;
    private _getSegmentBytes;
    private _makeSegmentMimeType;
    private _getSegmentTimelineBegin;
    private _getSegmentTimelineEnd;
}
export default MSEBufferStateMachine;
