import type PlayerEngine from './player-engine';
import MediaInfo from '../core/media-info';
declare class PlayerEngineDedicatedThread implements PlayerEngine {
    private readonly TAG;
    private _emitter;
    private _media_data_source;
    private _config;
    private _media_element?;
    private _worker;
    private _worker_destroying;
    private _seeking_handler?;
    private _loading_controller?;
    private _startup_buffer_gate?;
    private _startup_stall_jumper?;
    private _live_latency_chaser?;
    private _live_latency_synchronizer?;
    private _pending_seek_time?;
    private _audio_track_switch_buffer_target?;
    private _selected_mmts_audio_packet_id?;
    private _mmts_audio_tracks;
    private _selected_mmts_video_packet_id?;
    private _mmts_video_tracks;
    private _worker_forward_buffer_info?;
    private _last_mse_buffer_full_log_time;
    private _resume_after_audio_track_switch_rebuild?;
    private _playback_timeline_generation;
    private _playback_transaction_id;
    private _active_playback_operation?;
    private _reserved_audio_playback_operations;
    private _reserved_video_playback_operations;
    private _media_info?;
    private _statistics_info?;
    private e?;
    private _prev_ready_state;
    private _prev_ready_state_current_time;
    static isSupported(): boolean;
    constructor(mediaDataSource: any, config: any);
    destroy(): void;
    on(event: string, listener: (...args: any[]) => void): void;
    off(event: string, listener: (...args: any[]) => void): void;
    attachMediaElement(mediaElement: HTMLMediaElement): void;
    detachMediaElement(): void;
    load(): void;
    unload(): void;
    play(): Promise<void>;
    pause(): void;
    seek(seconds: number): void;
    switchPrimaryAudio(): void;
    switchSecondaryAudio(): void;
    selectAudioTrack(packetId: number): void;
    selectVideoTrack(packetId: number): void;
    get mediaInfo(): MediaInfo;
    get statisticsInfo(): any;
    private _getAudioTrackSwitchTimelineSeed;
    private _isMMTSVodAudioTrackSwitch;
    private _getAudioTrackSwitchPrerollTime;
    private _getStartupBufferDuration;
    private _getStartupGateForwardBufferDuration;
    private _getStallJumpMaxGap;
    private _getStallJumpMinBuffer;
    private _allowStallJumperRangeGapJump;
    private _beginAudioTrackSwitchBufferCatchup;
    private _updateAudioTrackSwitchBufferCatchup;
    _onLoggingConfigChanged(config: any): void;
    private _onMSEUpdateEnd;
    private _onMSEBufferFull;
    private _logMSEBufferFull;
    private _onMediaLoadedMetadata;
    private _onRequestDirectSeek;
    private _onControlledSeekRequest;
    private _onRequiredUnbufferedSeek;
    private _cancelMMTSAudioTrackSwitchResumeForSeek;
    private _onRequestPauseTransmuxer;
    private _onRequestResumeTransmuxer;
    private _onMediaTimeUpdate;
    private _onMediaReadyStateChange;
    private _onWorkerMessage;
    private _beginPlaybackOperation;
    private _reservePlaybackOperation;
    private _getMMTSAudioTrackTarget;
    private _reserveAudioPlaybackOperations;
    private _reserveVideoPlaybackOperations;
    private _acceptPlaybackOperation;
    private _fillStatisticsInfo;
}
export default PlayerEngineDedicatedThread;
