declare class SeekingHandler {
    private readonly TAG;
    private _config;
    private _media_element;
    private _always_seek_keyframe;
    private _on_unbuffered_seek;
    private _on_seek_request?;
    private _request_set_current_time;
    private _seek_request_record_clocktime?;
    private _controlled_media_seek_timer?;
    private _controlled_media_seek_target?;
    private _idr_sample_list;
    private e?;
    constructor(config: any, media_element: HTMLMediaElement, on_unbuffered_seek: (milliseconds: number) => void, on_seek_request?: (seconds: number, source: string) => boolean);
    destroy(): void;
    seek(seconds: number): void;
    directSeek(seconds: number): void;
    appendSyncPoints(syncpoints: any[]): void;
    private _onMediaSeeking;
    private _applyMediaSeeking;
    private _shouldCoalesceControlledMediaSeek;
    private _scheduleControlledMediaSeek;
    private _getControlledSeekDebounceInterval;
    private _cancelControlledMediaSeek;
    private _pollAndApplyUnbufferedSeek;
    private _applyUnbufferedSeek;
    isPositionBuffered(seconds: number): boolean;
    private _requestControlledSeek;
    private _clampLiveSeekTarget;
    private _getLiveSeekableRange;
    private _getLastValidRange;
    private _getNearestKeyframe;
    private static _getClockTime;
}
export default SeekingHandler;
