declare class StartupBufferGate {
    private readonly TAG;
    private _media_element;
    private _min_forward_buffer;
    private _get_forward_buffer_duration?;
    private _on_startup_jump?;
    private _requires_startup_group;
    private _startup_group_released;
    private _released;
    private _resume_requested;
    private _holding_playback;
    private _hold_logged;
    private _play_request_id;
    private _activation_play_pending;
    private _activation_hold_abort_expected;
    private _last_startup_jump_target;
    private _deferred_play_promise?;
    private _resolve_deferred_play?;
    private _reject_deferred_play?;
    private e;
    constructor(media_element: HTMLMediaElement, min_forward_buffer: number, get_forward_buffer_duration?: () => number, require_startup_group?: boolean, on_startup_jump?: (target: number) => boolean | void);
    destroy(): void;
    requestPlay(): Promise<void>;
    cancelPendingPlay(): void;
    notifyBufferedRangeUpdate(): void;
    releaseStartupGroup(): void;
    private _isEnabled;
    private _onMediaPlay;
    private _onMediaPause;
    private _onBufferedRangeUpdate;
    private _holdPlaybackIfNeeded;
    private _tryRelease;
    private _hasEnoughInitialBuffer;
    private _moveToBufferedStartupRange;
    private _getForwardBufferDuration;
    private _handleActivationPlayFailure;
    private _isAbortError;
    private _ensureDeferredPlayPromise;
    private _resolveDeferredPlay;
    private _rejectDeferredPlay;
    private _createAbortError;
}
export default StartupBufferGate;
