declare class StartupStallJumper {
    private readonly TAG;
    private _media_element;
    private _on_direct_seek;
    private _canplay_received;
    private _last_jump_target;
    private _last_jump_clock;
    private _stall_check_timer;
    private _stall_check_time;
    private _max_jump_gap;
    private _min_jump_buffer;
    private _allow_range_gap_jump;
    private _use_buffered_jump;
    private _defer_stalled_jump;
    private _conservative_in_range_recovery;
    private _on_continuous_buffer_stall;
    private e;
    constructor(media_element: HTMLMediaElement, on_direct_seek: (target: number) => boolean | void, max_jump_gap?: number, min_jump_buffer?: number, allow_range_gap_jump?: boolean, use_buffered_jump?: boolean, defer_stalled_jump?: boolean, conservative_in_range_recovery?: boolean, on_continuous_buffer_stall?: () => void);
    destroy(): void;
    private _onMediaCanPlay;
    private _onMediaPlaying;
    private _onMediaStalled;
    private _onMediaWaiting;
    private _onMediaProgress;
    private _detectAndFixStuckPlayback;
    private _findJumpTarget;
    private _findBufferedJumpTarget;
    private _getRangeGapJumpTarget;
    private _scheduleStallCheck;
    private _clearStallCheckTimer;
    private _onStallCheckTimer;
    private _findSmallForwardJumpTarget;
    private _shouldJumpTo;
    private _requestJump;
    private static _getClockTime;
}
export default StartupStallJumper;
